.PHONY: clean all

all:
	(cd ssl2 && $(MAKE) all)
	(cd ssl3 && $(MAKE) all)
	(cd tls10 && $(MAKE) all)
	(cd tls11 && $(MAKE) all)
	(cd tls12 && $(MAKE) all)
	(cd tls13 && $(MAKE) all)
	(cd features && $(MAKE) all)
	(cd workers && $(MAKE) all)

clean:
	(cd ssl2 && $(MAKE) clean)
	(cd ssl3 && $(MAKE) clean)
	(cd tls10 && $(MAKE) clean)
	(cd tls11 && $(MAKE) clean)
	(cd tls12 && $(MAKE) clean)
	(cd tls13 && $(MAKE) clean)
	(cd features && $(MAKE) clean)
	(cd workers && $(MAKE) clean)
