#!/bin/bash
SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

usage() {
    cat <<EOF
Usage: start_openssl2 <options>

Starts a openssl server.

List of options:
    -h, --help          Print this help
    --version           The openssl version to use. Currently supported:
                        openssl3_0_0, openssl1_1_1, openssl1_0_2,
                        openssl1_0_1g, openssl1_0_1e
    --port <int>        The listening port for the openssl server.
                        Can be set as well via the environment variable
                        TLSMATE_SERVER_PORT. Defaults to 44330.
    --cert1 <str>       The certificate, key and certificate chain to select.
                        The string is the name of the certificate/key/chain
                        file without extension.
    --cert2 <str>       Same as --cert1. It is a secondary option to select
                        another certificate.
    --cert3 <str>       Same as --cert1. It is yet another option to select
                        another certificate.
    --                  Indicates the end of the options for this script.
                        All following options will be passed transparently
                        to the openssl command.
EOF
    exit 1
}

port=44330
version=openssl3_0_0
cert1=server-rsa

if [ -n "$TLSMATE_SERVER_PORT" ]; then
    port=$TLSMATE_SERVER_PORT
fi

while [[ "$#" -gt 0 ]]; do
    case $1 in
        -h|--help) usage ;;
        --version) version="$2"; shift;;
        --port) port="$2"; shift;;
        --cert1) cert1="$2"; shift;;
        --cert2) cert2="$2"; shift;;
        --cert3) cert3="$2"; shift;;
        --) shift; break ;;
        *) echo "Unknown option $1"; usage; exit 1 ;;
    esac
    shift
done

openssl_path=$SCRIPTPATH/../openssl/$version
if [ -z "$OPENSSL" ]; then
    OPENSSL=$openssl_path/apps/openssl
    export LD_LIBRARY_PATH=$openssl_path:$LD_LIBRARY_PATH
fi
ca_dir=$SCRIPTPATH/../ca
if [ -n "$cert1" ]; then
    cert_params1=" -key $ca_dir/private/$cert1.key -cert $ca_dir/certs/$cert1.crt -cert_chain $ca_dir/chains/$cert1.chn"
fi
if [ -n "$cert2" ]; then
    cert_params2=" -dkey $ca_dir/private/$cert2.key -dcert $ca_dir/certs/$cert2.crt -dcert_chain $ca_dir/chains/$cert2.chn"
fi
if [ -n "$cert3" ]; then
    cert_params3=" -xkey $ca_dir/private/$cert3.key -xcert $ca_dir/certs/$cert3.crt -xchain $ca_dir/chains/$cert3.chn"
fi

kill `lsof -t -i :$port`
cmd="$OPENSSL s_server $cert_params1 $cert_params2 $cert_params3 -accept $port $@"
echo "Library path: $LD_LIBRARY_PATH"
echo $cmd
$cmd
